name: 🐛 Bug Report
labels: ["bug", "untriaged"]
description: Let us know if something is expected to work, but doesn't.
body:
  - type: markdown
    attributes:
      value: Before submitting a bug report, please check if there is an existing issue related to the problem you are experiencing. If one exists, provide any additional information in the comments instead of creating a new issue.
  - type: textarea
    id: describe-problem
    attributes:
      label: Describe the problem
      description: Describe the issue you are experiencing. Provide a clear and concise description of what you were trying to do, what happened, and any error messages you encountered.
    validations:
      required: true
  - type: input
    id: application-version
    attributes:
      label: Release version
      description: 'Enter the release version where you encountered the issue (example: 1.0.0).'
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: Operating system
      description: 'Enter the specific operating system version you are running (example: Windows 10)'
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the behavior
      description: Provide steps to reproduce the problem you are experiencing.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Provide additional context about the problem you are experiencing, such as links or references. Include any information that will offer more insight into the issue you are encountering.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain your problem, if applicable.
  - type: textarea
    id: logs
    attributes:
      label: Log files
      description: Please upload a log file from a day you experienced the issue, if applicable.
      placeholder: You can attach log files by clicking this area to highlight it and then dragging the files in.
