name: release-obfuscator-common
on:
  workflow_dispatch:
env:
  PROJECT: Dax.Vpax.Obfuscator.Common
jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: nbgv
      uses: dotnet/nbgv@v0.4
      id: nbgv
      with:
        path: src/${{ env.PROJECT }}
    - name: dotnet pack
      run: dotnet pack -c Release 'src/${{ env.PROJECT }}/${{ env.PROJECT }}.csproj'
    - name: nuget push
      run: echo "::warning::(TOFIX) enable nuget push."
    - name: create release
      run: |
        PRERELEASE_FLAG=$([[ "${{ steps.nbgv.outputs.PrereleaseVersion }}" != "" ]] && echo "--prerelease" || echo "")
        gh release create ${{ env.RELEASE_TAG }} --title ${{ env.RELEASE_TAG }} --target $GITHUB_SHA --generate-notes --draft $PRERELEASE_FLAG
      env:
        RELEASE_TAG: ${{ env.PROJECT }}_${{ steps.nbgv.outputs.NuGetPackageVersion }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
