name: release-obfuscator-common
on:
  workflow_dispatch:
env:
  PROJECT_NAME: Dax.Vpax.Obfuscator.Common
  PROJECT_PATH: src/Dax.Vpax.Obfuscator.Common
  PROJECT_FILE: Dax.Vpax.Obfuscator.Common.csproj
jobs:
  publish:
    #if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: nbgv
      uses: dotnet/nbgv@v0.4
      id: nbgv
      with:
        path: ${{ env.PROJECT_PATH }}
    - name: dotnet pack
      run: dotnet pack -c Release -o . '${{ env.PROJECT_PATH }}/${{ env.PROJECT_FILE }}'
    - name: nuget push
      run: dotnet nuget push '${{ env.PROJECT_NAME }}.${{ steps.nbgv.outputs.NuGetPackageVersion }}.nupkg' -k '${{ secrets.NUGET_API_KEY }}' -s https://api.nuget.org/v3/index.json
    - name: create release
      run: |
        RELEASE_TAG=${{ env.PROJECT_NAME }}_${{ steps.nbgv.outputs.NuGetPackageVersion }}
        PRERELEASE_FLAG=$([[ "${{ steps.nbgv.outputs.PrereleaseVersion }}" != "" ]] && echo "--prerelease" || echo "")
        gh release create $RELEASE_TAG --title $RELEASE_TAG --target $GITHUB_SHA --generate-notes --draft $PRERELEASE_FLAG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
